services:
  - type: web
    name: traffic-management
    env: node
    buildCommand: npm install && cd frontend && npm install --legacy-peer-deps && CI=false npm run build && cd .. && node copy-build.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
